#define	DERBY_UPDATE_DELAY			200
#define	DERBY_MIN_PLAYERS			2
#define	DERBY_MAX_PLAYERS			20
#define	DERBY_START_DELAY			50	//	Delay untill start of derby after first two players joined
#define	DERBY_COUNTDOWN_TIME		3000
#define	DERBY_COUNTDOWN_DT			1000	//	Conditions: DERBY_COUNTDOWN_TIME % DERBY_COUNTDOWN_DT == 0 && DERBY_COUNTDOWN_DT % 1000 == 0
#define	DERBY_COUNTDOWN_TEXT_STYLE	4
#define	DERBY_TOTAL_TIME			120000
#define	DERBY_RESTART_DELAY			5000
#define	DERBY_KICKVOTES				3		//	3 votes will remove the player from the derby
#define	DERBY_MESSAGE_COLOR			0x00FF1EFF
#define	DERBY_EXTRA_STARTING_HEIGHT	1.0
#define	DERBY_WEAPON_ID				WEAPON_ROCKETLAUNCHER
#define	DERBY_WEAPON_AMMO			9999999
#define	DERBY_DEATH_DZ				7.0		//	How far the player has to be under starting position to lose
#define DERBY_PLAYER_ALIVE			1
#define	DERBY_PLAYER_DEAD			0
#define	DERBY_DEATH_INTERVAL		300
#define	DERBY_DRAW_DISTANCE			500.0
#define	DERBY_ENABLE_NITRO			true

#define	DEFAULT_WORLD		0
#define	WEAPON_SLOTS		13
#define	MAX_CLIENT_MESSAGE	144